### ISSUE TITLE
Problem with composer install --no-dev

### ISSUE THREAD

**Issue by thanhtung2693** [ctf0/PackageChangeLog#4]
Hi, when I run ``composer install --no-dev``, I got this error:

![image](https://user-images.githubusercontent.com/4317955/106100533-1403f580-616f-11eb-9d69-1a49cb03d09e.png)

Also, Is there anyway I can prevent the package from adding scripts again?
I try adding this to composer.json but didn't work:

```
"laravel": {
    "dont-discover": [
         "ctf0/package-changelog"
     ]
}
```

Many thanks.

**Comment by ctf0** [comment]
have u tried https://github.com/ctf0/PackageChangeLog#uninstall ?

**Comment by thanhtung2693** [comment]
I cannot remove the package because I'm using [Laravel Media](https://github.com/ctf0/Laravel-Media-Manager) :laughing:

**Comment by ctf0** [comment]
u dont need to remove the package, just remove the scripts from composer & see if it fix ur issue.

**Comment by thanhtung2693** [comment]
Yep I can fix the problem by removing the scripts manually, but after I run `php artisan cache:clear`, the package will add the scripts again.

**Comment by ctf0** [comment]
yeah, well i havent tested with `composer install --no-dev` b4, so i cant really tell why u r getting this issue but still try to install the `dev-master` of the media manager while having 
```
"dont-discover": [
         "ctf0/package-changelog"
     ]
```

under the app `composer.json` & reply back.

**Comment by thanhtung2693** [comment]
Sure, it works without updating "dont-discover" directive. Thank you.
